#!/bin/sh

branch_name=$(git rev-parse --abbrev-ref HEAD)
remote_branch_name=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2> /dev/null)
remote_branch_name=${remote_branch_name:-origin/${branch_name}}

if [[ "${branch_name}" == "main" || "${branch_name}" == "master"
    || "${remote_branch_name}" == "origin/main" || "${remote_branch_name}" == "origin/master" ]]; then
    echo "Push denied to branch: ${branch_name}" 1>&2
    exit 1
fi

if ! [[ "${branch_name}" =~ "${USER}"* && "${remote_branch_name}" =~ "origin/${USER}"* ]]; then
    echo "Push denied to branch: ${branch_name} (must start with ${USER})" 1>&2
    exit 1
fi
